"""add birth_date to profile

Revision ID: 0350900c188b
Revises: 1349cbcd118d
Create Date: 2025-03-10 17:45:34.374759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0350900c188b'
down_revision = '1349cbcd118d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('birth_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'birth_date')
    # ### end Alembic commands ###