"""add birth_date to profile

Revision ID: 1349cbcd118d
Revises: 8b502687daa4
Create Date: 2025-03-10 17:42:17.430636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1349cbcd118d'
down_revision = '8b502687daa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###