"""add backend_url to profile_pictures

Revision ID: 9e114f1d18cb
Revises: fdab7860d953
Create Date: 2025-03-11 22:34:26.841718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e114f1d18cb'
down_revision = 'fdab7860d953'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_pictures', 'backend_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('reports', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'description')
    op.alter_column('profile_pictures', 'backend_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###